# encoding: utf-8

desc "Populate countries"
task :populate_countries => [:environment] do
  Addresses::Country.create(id: '4', name: 'Afeganistão', acronym: 'AFG') 
  Addresses::Country.create(id: '5', name: 'África do Sul', acronym: 'AFS') 
  Addresses::Country.create(id: '6', name: 'Antilhas Holandesas', acronym: 'AHL') 
  Addresses::Country.create(id: '7', name: 'Albânia', acronym: 'ALB') 
  Addresses::Country.create(id: '8', name: 'Antigua', acronym: 'ANB') 
  Addresses::Country.create(id: '9', name: 'Andorra', acronym: 'AND') 
  Addresses::Country.create(id: '10', name: 'Angola', acronym: 'ANG') 
  Addresses::Country.create(id: '11', name: 'Arábia Saudita', acronym: 'ARA') 
  Addresses::Country.create(id: '12', name: 'Argentina', acronym: 'ARG') 
  Addresses::Country.create(id: '13', name: 'Argélia', acronym: 'ARL') 
  Addresses::Country.create(id: '14', name: 'Armênia', acronym: 'ARM') 
  Addresses::Country.create(id: '15', name: 'Samoa Americana', acronym: 'ASM') 
  Addresses::Country.create(id: '16', name: 'Antartida', acronym: 'ATC') 
  Addresses::Country.create(id: '17', name: 'Austrália', acronym: 'AUS') 
  Addresses::Country.create(id: '18', name: 'Austria', acronym: 'AUT') 
  Addresses::Country.create(id: '19', name: 'Azerbaijão', acronym: 'AZE') 
  Addresses::Country.create(id: '20', name: 'Barein', acronym: 'BAR') 
  Addresses::Country.create(id: '21', name: 'Belarus', acronym: 'BEA') 
  Addresses::Country.create(id: '22', name: 'Bélgica', acronym: 'BEL') 
  Addresses::Country.create(id: '23', name: 'Benin', acronym: 'BEN') 
  Addresses::Country.create(id: '24', name: 'Bermudas', acronym: 'BER') 
  Addresses::Country.create(id: '25', name: 'Bangladesh', acronym: 'BGD') 
  Addresses::Country.create(id: '26', name: 'Bahamas', acronym: 'BHS') 
  Addresses::Country.create(id: '27', name: 'Birmânia', acronym: 'BIR') 
  Addresses::Country.create(id: '28', name: 'Burkina Fasso', acronym: 'BKF') 
  Addresses::Country.create(id: '29', name: 'Belize', acronym: 'BLZ') 
  Addresses::Country.create(id: '30', name: 'Bolívia', acronym: 'BOL') 
  Addresses::Country.create(id: '31', name: 'Bósnia', acronym: 'BOS') 
  Addresses::Country.create(id: '32', name: 'Botsuana', acronym: 'BOT') 
  Addresses::Country.create(id: '33', name: 'Brasil', acronym: 'BRA') 
  Addresses::Country.create(id: '34', name: 'Barbados', acronym: 'BRB') 
  Addresses::Country.create(id: '35', name: 'Brunei', acronym: 'BRN') 
  Addresses::Country.create(id: '36', name: 'Bulgária', acronym: 'BUL') 
  Addresses::Country.create(id: '37', name: 'Burundi', acronym: 'BUR') 
  Addresses::Country.create(id: '38', name: 'Butão', acronym: 'BUT') 
  Addresses::Country.create(id: '39', name: 'Camarões', acronym: 'CAM') 
  Addresses::Country.create(id: '40', name: 'Canadá', acronym: 'CAN') 
  Addresses::Country.create(id: '41', name: 'Catar', acronym: 'CAT') 
  Addresses::Country.create(id: '42', name: 'Cazaquistão', acronym: 'CAZ') 
  Addresses::Country.create(id: '43', name: 'Camboja', acronym: 'CBJ') 
  Addresses::Country.create(id: '44', name: 'Cabo Verde', acronym: 'CBV') 
  Addresses::Country.create(id: '45', name: 'Ilhas Cocos', acronym: 'CCK') 
  Addresses::Country.create(id: '46', name: 'Chade', acronym: 'CHA') 
  Addresses::Country.create(id: '47', name: 'Chile', acronym: 'CHL') 
  Addresses::Country.create(id: '48', name: 'China', acronym: 'CHN') 
  Addresses::Country.create(id: '49', name: 'Chipre', acronym: 'CHP') 
  Addresses::Country.create(id: '50', name: 'Cingapura', acronym: 'CIN') 
  Addresses::Country.create(id: '51', name: 'Costa do Marfim', acronym: 'CMF') 
  Addresses::Country.create(id: '52', name: 'Ilhas Cook', acronym: 'COK') 
  Addresses::Country.create(id: '53', name: 'Colômbia', acronym: 'COL') 
  Addresses::Country.create(id: '54', name: 'Comores', acronym: 'COM') 
  Addresses::Country.create(id: '55', name: 'Congo', acronym: 'CON') 
  Addresses::Country.create(id: '56', name: 'Costa Rica', acronym: 'CRC') 
  Addresses::Country.create(id: '57', name: 'Coréia do Norte', acronym: 'CRN') 
  Addresses::Country.create(id: '58', name: 'Croácia', acronym: 'CRO') 
  Addresses::Country.create(id: '59', name: 'Coréia do Sul', acronym: 'CRS') 
  Addresses::Country.create(id: '60', name: 'Cuba', acronym: 'CUB') 
  Addresses::Country.create(id: '61', name: 'Christmas Island', acronym: 'CXR') 
  Addresses::Country.create(id: '62', name: 'Ilhas Cayman', acronym: 'CYM') 
  Addresses::Country.create(id: '63', name: 'Dinamarca', acronym: 'DIN') 
  Addresses::Country.create(id: '64', name: 'Djibuti', acronym: 'DJI') 
  Addresses::Country.create(id: '65', name: 'República Dominicana', acronym: 'DOM') 
  Addresses::Country.create(id: '66', name: 'Dominica', acronym: 'DON') 
  Addresses::Country.create(id: '67', name: 'Emirados Árabes', acronym: 'EAU') 
  Addresses::Country.create(id: '68', name: 'Egito', acronym: 'EGI') 
  Addresses::Country.create(id: '69', name: 'El Salvador', acronym: 'ELS') 
  Addresses::Country.create(id: '70', name: 'Equador', acronym: 'EQU') 
  Addresses::Country.create(id: '71', name: 'Eritréa', acronym: 'ERT') 
  Addresses::Country.create(id: '72', name: 'Escócia', acronym: 'ESC') 
  Addresses::Country.create(id: '73', name: 'Western Sahara', acronym: 'ESH') 
  Addresses::Country.create(id: '74', name: 'Espanha', acronym: 'ESP') 
  Addresses::Country.create(id: '75', name: 'Estônia', acronym: 'EST') 
  Addresses::Country.create(id: '76', name: 'Etiópia', acronym: 'ETP') 
  Addresses::Country.create(id: '77', name: 'Estados Unidos', acronym: 'EUA') 
  Addresses::Country.create(id: '78', name: 'Filipinas', acronym: 'FIL') 
  Addresses::Country.create(id: '79', name: 'Finlândia', acronym: 'FIN') 
  Addresses::Country.create(id: '80', name: 'Fiji', acronym: 'FJI') 
  Addresses::Country.create(id: '81', name: 'Ilhas Falkland', acronym: 'FLK') 
  Addresses::Country.create(id: '82', name: 'Formosa', acronym: 'FOR') 
  Addresses::Country.create(id: '83', name: 'França', acronym: 'FRA') 
  Addresses::Country.create(id: '84', name: 'Micronésia', acronym: 'FSM') 
  Addresses::Country.create(id: '85', name: 'Gabão', acronym: 'GAB') 
  Addresses::Country.create(id: '86', name: 'Gales', acronym: 'GAL') 
  Addresses::Country.create(id: '87', name: 'Gâmbia', acronym: 'GAM') 
  Addresses::Country.create(id: '88', name: 'Gana', acronym: 'GAN') 
  Addresses::Country.create(id: '89', name: 'Grã-Bretanha', acronym: 'GBR') 
  Addresses::Country.create(id: '90', name: 'Guadalupe', acronym: 'GDL') 
  Addresses::Country.create(id: '91', name: 'Geórgia', acronym: 'GEO') 
  Addresses::Country.create(id: '92', name: 'Guiana Francesa', acronym: 'GFR') 
  Addresses::Country.create(id: '93', name: 'Gibraltar', acronym: 'GIB') 
  Addresses::Country.create(id: '94', name: 'Guiné Bissau', acronym: 'GNB') 
  Addresses::Country.create(id: '95', name: 'Guiné', acronym: 'GNE') 
  Addresses::Country.create(id: '96', name: 'Guiné Equatorial', acronym: 'GNQ') 
  Addresses::Country.create(id: '97', name: 'Granada', acronym: 'GRD') 
  Addresses::Country.create(id: '98', name: 'Grécia', acronym: 'GRE') 
  Addresses::Country.create(id: '99', name: 'Groênlandia', acronym: 'GRL') 
  Addresses::Country.create(id: '100', name: 'Guatemala', acronym: 'GUA') 
  Addresses::Country.create(id: '101', name: 'Guiana', acronym: 'GUI') 
  Addresses::Country.create(id: '102', name: 'Guam', acronym: 'GUM') 
  Addresses::Country.create(id: '103', name: 'Hong Kong', acronym: 'HKG') 
  Addresses::Country.create(id: '104', name: 'Holanda', acronym: 'HOL') 
  Addresses::Country.create(id: '105', name: 'Honduras', acronym: 'HON') 
  Addresses::Country.create(id: '106', name: 'Haiti', acronym: 'HTI') 
  Addresses::Country.create(id: '107', name: 'Hungria', acronym: 'HUN') 
  Addresses::Country.create(id: '108', name: 'Indonésia', acronym: 'IDN') 
  Addresses::Country.create(id: '109', name: 'Iêmem', acronym: 'IEM') 
  Addresses::Country.create(id: '110', name: 'Ilhas Faroe', acronym: 'IFA') 
  Addresses::Country.create(id: '111', name: 'Ilhas Marshall', acronym: 'IMH') 
  Addresses::Country.create(id: '112', name: 'Iêmen do Sul', acronym: 'IMS') 
  Addresses::Country.create(id: '113', name: 'Índia', acronym: 'IND') 
  Addresses::Country.create(id: '114', name: 'Inglaterra', acronym: 'ING') 
  Addresses::Country.create(id: '115', name: 'Britsh Indian Ocean', acronym: 'IOT') 
  Addresses::Country.create(id: '116', name: 'Irã', acronym: 'IRA') 
  Addresses::Country.create(id: '117', name: 'Irlanda', acronym: 'IRL') 
  Addresses::Country.create(id: '118', name: 'Irlanda do Norte', acronym: 'IRN') 
  Addresses::Country.create(id: '119', name: 'Iraque', acronym: 'IRQ') 
  Addresses::Country.create(id: '120', name: 'Islândia', acronym: 'ISL') 
  Addresses::Country.create(id: '121', name: 'Israel', acronym: 'ISR') 
  Addresses::Country.create(id: '122', name: 'Itália', acronym: 'ITA') 
  Addresses::Country.create(id: '123', name: 'Iugoslávia', acronym: 'IUG') 
  Addresses::Country.create(id: '124', name: 'Ilhas Vírgens EUA', acronym: 'IVA') 
  Addresses::Country.create(id: '125', name: 'Jamaica', acronym: 'JAM') 
  Addresses::Country.create(id: '126', name: 'Japão', acronym: 'JAP') 
  Addresses::Country.create(id: '127', name: 'Jordânia', acronym: 'JOR') 
  Addresses::Country.create(id: '128', name: 'Kiribati', acronym: 'KIR') 
  Addresses::Country.create(id: '129', name: 'São Cristóvão Nevis', acronym: 'KNA') 
  Addresses::Country.create(id: '130', name: 'Kuweit', acronym: 'KWT') 
  Addresses::Country.create(id: '131', name: 'Laos', acronym: 'LAO') 
  Addresses::Country.create(id: '132', name: 'Líbano', acronym: 'LBN') 
  Addresses::Country.create(id: '133', name: 'Libéria', acronym: 'LBR') 
  Addresses::Country.create(id: '134', name: 'Santa Lúcia', acronym: 'LCA') 
  Addresses::Country.create(id: '135', name: 'Lesoto', acronym: 'LES') 
  Addresses::Country.create(id: '136', name: 'Letônia', acronym: 'LET') 
  Addresses::Country.create(id: '137', name: 'Líbia', acronym: 'LIB') 
  Addresses::Country.create(id: '138', name: 'Liechtenstein', acronym: 'LIE') 
  Addresses::Country.create(id: '139', name: 'Lituânia', acronym: 'LIT') 
  Addresses::Country.create(id: '140', name: 'Luxemburgo', acronym: 'LUX') 
  Addresses::Country.create(id: '141', name: 'Macau', acronym: 'MAC') 
  Addresses::Country.create(id: '142', name: 'Madagascar', acronym: 'MAD') 
  Addresses::Country.create(id: '143', name: 'Malásia', acronym: 'MAL') 
  Addresses::Country.create(id: '144', name: 'Marrocos', acronym: 'MAR') 
  Addresses::Country.create(id: '145', name: 'Maurício', acronym: 'MAU') 
  Addresses::Country.create(id: '146', name: 'Moçambique', acronym: 'MBQ') 
  Addresses::Country.create(id: '147', name: 'Macedônia', acronym: 'MCD') 
  Addresses::Country.create(id: '148', name: 'Maldivas', acronym: 'MDV') 
  Addresses::Country.create(id: '149', name: 'México', acronym: 'MEX') 
  Addresses::Country.create(id: '150', name: 'Mongólia', acronym: 'MGL') 
  Addresses::Country.create(id: '151', name: 'Ilhas Midway', acronym: 'MID') 
  Addresses::Country.create(id: '152', name: 'Mali', acronym: 'MLI') 
  Addresses::Country.create(id: '153', name: 'Malta', acronym: 'MLT') 
  Addresses::Country.create(id: '154', name: 'Malavi', acronym: 'MLV') 
  Addresses::Country.create(id: '155', name: 'Mianmar', acronym: 'MMR') 
  Addresses::Country.create(id: '156', name: 'Moldova', acronym: 'MOL') 
  Addresses::Country.create(id: '157', name: 'Mônaco', acronym: 'MON') 
  Addresses::Country.create(id: '158', name: 'Martinica', acronym: 'MRT') 
  Addresses::Country.create(id: '159', name: 'Montserrat', acronym: 'MSR') 
  Addresses::Country.create(id: '160', name: 'Mauritânia', acronym: 'MTN') 
  Addresses::Country.create(id: '161', name: 'Namíbia', acronym: 'NAM') 
  Addresses::Country.create(id: '162', name: 'Nova Caledônia', acronym: 'NCL') 
  Addresses::Country.create(id: '163', name: 'Ilhas Norfolk', acronym: 'NFK') 
  Addresses::Country.create(id: '164', name: 'Nigéria', acronym: 'NGA') 
  Addresses::Country.create(id: '165', name: 'Nicarágua', acronym: 'NIC') 
  Addresses::Country.create(id: '166', name: 'Niger', acronym: 'NIG') 
  Addresses::Country.create(id: '167', name: 'Niue', acronym: 'NIU') 
  Addresses::Country.create(id: '168', name: 'Noruega', acronym: 'NOR') 
  Addresses::Country.create(id: '169', name: 'Nepal', acronym: 'NPL') 
  Addresses::Country.create(id: '170', name: 'Nauru', acronym: 'NRU') 
  Addresses::Country.create(id: '171', name: 'Nova Zelândia', acronym: 'NZL') 
  Addresses::Country.create(id: '172', name: 'Oma', acronym: 'OMA') 
  Addresses::Country.create(id: '173', name: 'Panamá', acronym: 'PAN') 
  Addresses::Country.create(id: '174', name: 'Paquistão', acronym: 'PAQ') 
  Addresses::Country.create(id: '175', name: 'Pacific Islands', acronym: 'PCI') 
  Addresses::Country.create(id: '176', name: 'Pitcairn', acronym: 'PCN') 
  Addresses::Country.create(id: '177', name: 'Peru', acronym: 'PER') 
  Addresses::Country.create(id: '178', name: 'Polinésia Francesa', acronym: 'PLF') 
  Addresses::Country.create(id: '179', name: 'Palau', acronym: 'PLU') 
  Addresses::Country.create(id: '180', name: 'Papua Nova Guiné', acronym: 'PNG') 
  Addresses::Country.create(id: '181', name: 'Polônia', acronym: 'POL') 
  Addresses::Country.create(id: '182', name: 'Portugal', acronym: 'POR') 
  Addresses::Country.create(id: '183', name: 'Paraguai', acronym: 'PRG') 
  Addresses::Country.create(id: '184', name: 'Porto Rico', acronym: 'PTR') 
  Addresses::Country.create(id: '185', name: 'Quênia', acronym: 'QUE') 
  Addresses::Country.create(id: '186', name: 'Quirgistão', acronym: 'QUI') 
  Addresses::Country.create(id: '187', name: 'Rep.Centro-Africana', acronym: 'RCA') 
  Addresses::Country.create(id: '188', name: 'Reunião', acronym: 'REU') 
  Addresses::Country.create(id: '189', name: 'Alemanha', acronym: 'RFA') 
  Addresses::Country.create(id: '190', name: 'Romênia', acronym: 'ROM') 
  Addresses::Country.create(id: '191', name: 'Rússia', acronym: 'RSS') 
  Addresses::Country.create(id: '192', name: 'Ruanda', acronym: 'RUA') 
  Addresses::Country.create(id: '193', name: 'Samoa Ocidental', acronym: 'SAM') 
  Addresses::Country.create(id: '194', name: 'Senegal', acronym: 'SEN') 
  Addresses::Country.create(id: '195', name: 'Ilhas Santa Helena', acronym: 'SHN') 
  Addresses::Country.create(id: '196', name: 'Síria', acronym: 'SIR') 
  Addresses::Country.create(id: '197', name: 'Ilhas Salamão', acronym: 'SLB') 
  Addresses::Country.create(id: '198', name: 'San Marino', acronym: 'SMR') 
  Addresses::Country.create(id: '199', name: 'Somália', acronym: 'SOM') 
  Addresses::Country.create(id: '200', name: 'São Pedro Miquelon', acronym: 'SPM') 
  Addresses::Country.create(id: '201', name: 'Sri Lanka', acronym: 'SRI') 
  Addresses::Country.create(id: '202', name: 'Serra Leoa', acronym: 'SRL') 
  Addresses::Country.create(id: '203', name: 'São Tomé e Príncipe', acronym: 'STP') 
  Addresses::Country.create(id: '204', name: 'Suazilândia', acronym: 'SUA') 
  Addresses::Country.create(id: '205', name: 'Sudão', acronym: 'SUD') 
  Addresses::Country.create(id: '206', name: 'Suécia', acronym: 'SUE') 
  Addresses::Country.create(id: '207', name: 'Suiça', acronym: 'SUI') 
  Addresses::Country.create(id: '208', name: 'Suriname', acronym: 'SUR') 
  Addresses::Country.create(id: '209', name: 'Eslováquia', acronym: 'SVK') 
  Addresses::Country.create(id: '210', name: 'Eslovênia', acronym: 'SVN') 
  Addresses::Country.create(id: '211', name: 'Seychelles', acronym: 'SYC') 
  Addresses::Country.create(id: '212', name: 'Tadjaquistão', acronym: 'TAD') 
  Addresses::Country.create(id: '213', name: 'Tailândia', acronym: 'TAI') 
  Addresses::Country.create(id: '214', name: 'Tanzânia', acronym: 'TAN') 
  Addresses::Country.create(id: '215', name: 'Ilhas Turcas Caicos', acronym: 'TCA') 
  Addresses::Country.create(id: '216', name: 'República Tcheca', acronym: 'TCH') 
  Addresses::Country.create(id: '217', name: 'Togo', acronym: 'TGO') 
  Addresses::Country.create(id: '218', name: 'Tokelau', acronym: 'TKL') 
  Addresses::Country.create(id: '219', name: 'Timor', acronym: 'TMP') 
  Addresses::Country.create(id: '220', name: 'Tonga', acronym: 'TON') 
  Addresses::Country.create(id: '221', name: 'Trinidad e Tobago', acronym: 'TRT') 
  Addresses::Country.create(id: '222', name: 'Turcomenistão', acronym: 'TUC') 
  Addresses::Country.create(id: '223', name: 'Tunísia', acronym: 'TUN') 
  Addresses::Country.create(id: '224', name: 'Turquia', acronym: 'TUR') 
  Addresses::Country.create(id: '225', name: 'Tuvalu', acronym: 'TUV') 
  Addresses::Country.create(id: '226', name: 'Ucrânia', acronym: 'UCR') 
  Addresses::Country.create(id: '227', name: 'Uganda', acronym: 'UGA') 
  Addresses::Country.create(id: '228', name: 'União Soviética', acronym: 'URS') 
  Addresses::Country.create(id: '229', name: 'Uruguai', acronym: 'URU') 
  Addresses::Country.create(id: '230', name: 'Uzbekistan', acronym: 'UZB') 
  Addresses::Country.create(id: '231', name: 'Vaticano', acronym: 'VAT') 
  Addresses::Country.create(id: '232', name: 'São Vicente Granadi', acronym: 'VCT') 
  Addresses::Country.create(id: '233', name: 'Venezuela', acronym: 'VEN') 
  Addresses::Country.create(id: '234', name: 'Ilhas Vírgens GBR', acronym: 'VGB') 
  Addresses::Country.create(id: '235', name: 'Vietnã', acronym: 'VTN') 
  Addresses::Country.create(id: '236', name: 'Vanuatu', acronym: 'VUT') 
  Addresses::Country.create(id: '237', name: 'Ilhas Wake', acronym: 'WAK') 
  Addresses::Country.create(id: '238', name: 'Ilhas Wallis Futuna', acronym: 'WLF') 
  Addresses::Country.create(id: '239', name: 'Zâmbia', acronym: 'ZAN') 
  Addresses::Country.create(id: '240', name: 'Zaire', acronym: 'ZAR') 
  Addresses::Country.create(id: '241', name: 'Zimbabue', acronym: 'ZIN')
end
