# encoding: utf-8
# frozen_string_literal: true

namespace :addresses do
  namespace :countries do
    desc 'Populate all countries in the world (names in pt-br)'
    task populate: :environment do
      # Add logic here to populate countries
      # Example:
      # Country.create!(name: 'Brazil', code: 'BR')
      puts 'Populando países do mundo...'
      Addresses::Country.find_or_create_by(id: 1, name: 'Afeganistão', acronym: 'AF')
      Addresses::Country.find_or_create_by(id: 2, name: 'África do Sul', acronym: 'ZA')
      Addresses::Country.find_or_create_by(id: 3, name: 'Albânia', acronym: 'AL')
      Addresses::Country.find_or_create_by(id: 4, name: 'Alemanha', acronym: 'DE')
      Addresses::Country.find_or_create_by(id: 5, name: 'Andorra', acronym: 'AD')
      Addresses::Country.find_or_create_by(id: 6, name: 'Angola', acronym: 'AO')
      Addresses::Country.find_or_create_by(id: 7, name: 'Antígua e Barbuda', acronym: 'AG')
      Addresses::Country.find_or_create_by(id: 8, name: 'Arábia Saudita', acronym: 'SA')
      Addresses::Country.find_or_create_by(id: 9, name: 'Argélia', acronym: 'DZ')
      Addresses::Country.find_or_create_by(id: 10, name: 'Argentina', acronym: 'AR')
      Addresses::Country.find_or_create_by(id: 11, name: 'Armênia', acronym: 'AM')
      Addresses::Country.find_or_create_by(id: 12, name: 'Austrália', acronym: 'AU')
      Addresses::Country.find_or_create_by(id: 13, name: 'Áustria', acronym: 'AT')
      Addresses::Country.find_or_create_by(id: 14, name: 'Azerbaijão', acronym: 'AZ')
      Addresses::Country.find_or_create_by(id: 15, name: 'Bahamas', acronym: 'BS')
      Addresses::Country.find_or_create_by(id: 16, name: 'Bangladesh', acronym: 'BD')
      Addresses::Country.find_or_create_by(id: 17, name: 'Barbados', acronym: 'BB')
      Addresses::Country.find_or_create_by(id: 18, name: 'Bahrein', acronym: 'BH')
      Addresses::Country.find_or_create_by(id: 19, name: 'Bélgica', acronym: 'BE')
      Addresses::Country.find_or_create_by(id: 20, name: 'Belize', acronym: 'BZ')
      Addresses::Country.find_or_create_by(id: 21, name: 'Benin', acronym: 'BJ')
      Addresses::Country.find_or_create_by(id: 22, name: 'Bielorrússia', acronym: 'BY')
      Addresses::Country.find_or_create_by(id: 23, name: 'Bolívia', acronym: 'BO')
      Addresses::Country.find_or_create_by(id: 24, name: 'Bósnia e Herzegovina', acronym: 'BA')
      Addresses::Country.find_or_create_by(id: 25, name: 'Botsuana', acronym: 'BW')
      Addresses::Country.find_or_create_by(id: 26, name: 'Brasil', acronym: 'BR')
      Addresses::Country.find_or_create_by(id: 27, name: 'Brunei', acronym: 'BN')
      Addresses::Country.find_or_create_by(id: 28, name: 'Bulgária', acronym: 'BG')
      Addresses::Country.find_or_create_by(id: 29, name: 'Burkina Faso', acronym: 'BF')
      Addresses::Country.find_or_create_by(id: 30, name: 'Burundi', acronym: 'BI')
      Addresses::Country.find_or_create_by(id: 31, name: 'Butão', acronym: 'BT')
      Addresses::Country.find_or_create_by(id: 32, name: 'Cabo Verde', acronym: 'CV')
      Addresses::Country.find_or_create_by(id: 33, name: 'Camarões', acronym: 'CM')
      Addresses::Country.find_or_create_by(id: 34, name: 'Camboja', acronym: 'KH')
      Addresses::Country.find_or_create_by(id: 35, name: 'Canadá', acronym: 'CA')
      Addresses::Country.find_or_create_by(id: 36, name: 'Catar', acronym: 'QA')
      Addresses::Country.find_or_create_by(id: 37, name: 'Cazaquistão', acronym: 'KZ')
      Addresses::Country.find_or_create_by(id: 38, name: 'Chade', acronym: 'TD')
      Addresses::Country.find_or_create_by(id: 39, name: 'Chile', acronym: 'CL')
      Addresses::Country.find_or_create_by(id: 40, name: 'China', acronym: 'CN')
      Addresses::Country.find_or_create_by(id: 41, name: 'Chipre', acronym: 'CY')
      Addresses::Country.find_or_create_by(id: 42, name: 'Colômbia', acronym: 'CO')
      Addresses::Country.find_or_create_by(id: 43, name: 'Comores', acronym: 'KM')
      Addresses::Country.find_or_create_by(id: 44, name: 'Congo', acronym: 'CG')
      Addresses::Country.find_or_create_by(id: 45, name: 'Coreia do Norte', acronym: 'KP')
      Addresses::Country.find_or_create_by(id: 46, name: 'Coreia do Sul', acronym: 'KR')
      Addresses::Country.find_or_create_by(id: 47, name: 'Costa do Marfim', acronym: 'CI')
      Addresses::Country.find_or_create_by(id: 48, name: 'Costa Rica', acronym: 'CR')
      Addresses::Country.find_or_create_by(id: 49, name: 'Croácia', acronym: 'HR')
      Addresses::Country.find_or_create_by(id: 50, name: 'Cuba', acronym: 'CU')
      Addresses::Country.find_or_create_by(id: 51, name: 'Dinamarca', acronym: 'DK')
      Addresses::Country.find_or_create_by(id: 52, name: 'Djibuti', acronym: 'DJ')
      Addresses::Country.find_or_create_by(id: 53, name: 'Dominica', acronym: 'DM')
      Addresses::Country.find_or_create_by(id: 54, name: 'Egito', acronym: 'EG')
      Addresses::Country.find_or_create_by(id: 55, name: 'El Salvador', acronym: 'SV')
      Addresses::Country.find_or_create_by(id: 56, name: 'Emirados Árabes Unidos', acronym: 'AE')
      Addresses::Country.find_or_create_by(id: 57, name: 'Equador', acronym: 'EC')
      Addresses::Country.find_or_create_by(id: 58, name: 'Eritreia', acronym: 'ER')
      Addresses::Country.find_or_create_by(id: 59, name: 'Eslováquia', acronym: 'SK')
      Addresses::Country.find_or_create_by(id: 60, name: 'Eslovênia', acronym: 'SI')
      Addresses::Country.find_or_create_by(id: 61, name: 'Espanha', acronym: 'ES')
      Addresses::Country.find_or_create_by(id: 62, name: 'Estados Unidos', acronym: 'US')
      Addresses::Country.find_or_create_by(id: 63, name: 'Estônia', acronym: 'EE')
      Addresses::Country.find_or_create_by(id: 64, name: 'Etiópia', acronym: 'ET')
      Addresses::Country.find_or_create_by(id: 65, name: 'Fiji', acronym: 'FJ')
      Addresses::Country.find_or_create_by(id: 66, name: 'Filipinas', acronym: 'PH')
      Addresses::Country.find_or_create_by(id: 67, name: 'Finlândia', acronym: 'FI')
      Addresses::Country.find_or_create_by(id: 68, name: 'França', acronym: 'FR')
      Addresses::Country.find_or_create_by(id: 69, name: 'Gabão', acronym: 'GA')
      Addresses::Country.find_or_create_by(id: 70, name: 'Gâmbia', acronym: 'GM')
      Addresses::Country.find_or_create_by(id: 71, name: 'Gana', acronym: 'GH')
      Addresses::Country.find_or_create_by(id: 72, name: 'Geórgia', acronym: 'GE')
      Addresses::Country.find_or_create_by(id: 73, name: 'Granada', acronym: 'GD')
      Addresses::Country.find_or_create_by(id: 74, name: 'Grécia', acronym: 'GR')
      Addresses::Country.find_or_create_by(id: 75, name: 'Guatemala', acronym: 'GT')
      Addresses::Country.find_or_create_by(id: 76, name: 'Guiana', acronym: 'GY')
      Addresses::Country.find_or_create_by(id: 77, name: 'Guiana Francesa', acronym: 'GF')
      Addresses::Country.find_or_create_by(id: 78, name: 'Guiné', acronym: 'GN')
      Addresses::Country.find_or_create_by(id: 79, name: 'Guiné-Bissau', acronym: 'GW')
      Addresses::Country.find_or_create_by(id: 80, name: 'Guiné Equatorial', acronym: 'GQ')
      Addresses::Country.find_or_create_by(id: 81, name: 'Haiti', acronym: 'HT')
      Addresses::Country.find_or_create_by(id: 82, name: 'Holanda', acronym: 'NL')
      Addresses::Country.find_or_create_by(id: 83, name: 'Honduras', acronym: 'HN')
      Addresses::Country.find_or_create_by(id: 84, name: 'Hungria', acronym: 'HU')
      Addresses::Country.find_or_create_by(id: 85, name: 'Iêmen', acronym: 'YE')
      Addresses::Country.find_or_create_by(id: 86, name: 'Ilhas Marshall', acronym: 'MH')
      Addresses::Country.find_or_create_by(id: 87, name: 'Ilhas Salomão', acronym: 'SB')
      Addresses::Country.find_or_create_by(id: 88, name: 'Índia', acronym: 'IN')
      Addresses::Country.find_or_create_by(id: 89, name: 'Indonésia', acronym: 'ID')
      Addresses::Country.find_or_create_by(id: 90, name: 'Inglaterra', acronym: 'GB')
      Addresses::Country.find_or_create_by(id: 91, name: 'Irã', acronym: 'IR')
      Addresses::Country.find_or_create_by(id: 92, name: 'Iraque', acronym: 'IQ')
      Addresses::Country.find_or_create_by(id: 93, name: 'Irlanda', acronym: 'IE')
      Addresses::Country.find_or_create_by(id: 94, name: 'Islândia', acronym: 'IS')
      Addresses::Country.find_or_create_by(id: 95, name: 'Israel', acronym: 'IL')
      Addresses::Country.find_or_create_by(id: 96, name: 'Itália', acronym: 'IT')
      Addresses::Country.find_or_create_by(id: 97, name: 'Jamaica', acronym: 'JM')
      Addresses::Country.find_or_create_by(id: 98, name: 'Japão', acronym: 'JP')
      Addresses::Country.find_or_create_by(id: 99, name: 'Jordânia', acronym: 'JO')
      Addresses::Country.find_or_create_by(id: 100, name: 'Kiribati', acronym: 'KI')
      Addresses::Country.find_or_create_by(id: 101, name: 'Kosovo', acronym: 'XK')
      Addresses::Country.find_or_create_by(id: 102, name: 'Kuwait', acronym: 'KW')
      Addresses::Country.find_or_create_by(id: 103, name: 'Laos', acronym: 'LA')
      Addresses::Country.find_or_create_by(id: 104, name: 'Lesoto', acronym: 'LS')
      Addresses::Country.find_or_create_by(id: 105, name: 'Letônia', acronym: 'LV')
      Addresses::Country.find_or_create_by(id: 106, name: 'Líbano', acronym: 'LB')
      Addresses::Country.find_or_create_by(id: 107, name: 'Libéria', acronym: 'LR')
      Addresses::Country.find_or_create_by(id: 108, name: 'Líbia', acronym: 'LY')
      Addresses::Country.find_or_create_by(id: 109, name: 'Liechtenstein', acronym: 'LI')
      Addresses::Country.find_or_create_by(id: 110, name: 'Lituânia', acronym: 'LT')
      Addresses::Country.find_or_create_by(id: 111, name: 'Luxemburgo', acronym: 'LU')
      Addresses::Country.find_or_create_by(id: 112, name: 'Macedônia do Norte', acronym: 'MK')
      Addresses::Country.find_or_create_by(id: 113, name: 'Madagáscar', acronym: 'MG')
      Addresses::Country.find_or_create_by(id: 114, name: 'Malásia', acronym: 'MY')
      Addresses::Country.find_or_create_by(id: 115, name: 'Malawi', acronym: 'MW')
      Addresses::Country.find_or_create_by(id: 116, name: 'Maldivas', acronym: 'MV')
      Addresses::Country.find_or_create_by(id: 117, name: 'Mali', acronym: 'ML')
      Addresses::Country.find_or_create_by(id: 118, name: 'Malta', acronym: 'MT')
      Addresses::Country.find_or_create_by(id: 119, name: 'Marrocos', acronym: 'MA')
      Addresses::Country.find_or_create_by(id: 120, name: 'Martinica', acronym: 'MQ')
      Addresses::Country.find_or_create_by(id: 121, name: 'Maurício', acronym: 'MU')
      Addresses::Country.find_or_create_by(id: 122, name: 'Mauritânia', acronym: 'MR')
      Addresses::Country.find_or_create_by(id: 123, name: 'México', acronym: 'MX')
      Addresses::Country.find_or_create_by(id: 124, name: 'Mianmar', acronym: 'MM')
      Addresses::Country.find_or_create_by(id: 125, name: 'Micronésia', acronym: 'FM')
      Addresses::Country.find_or_create_by(id: 126, name: 'Moçambique', acronym: 'MZ')
      Addresses::Country.find_or_create_by(id: 127, name: 'Moldávia', acronym: 'MD')
      Addresses::Country.find_or_create_by(id: 128, name: 'Mônaco', acronym: 'MC')
      Addresses::Country.find_or_create_by(id: 129, name: 'Mongólia', acronym: 'MN')
      Addresses::Country.find_or_create_by(id: 130, name: 'Montenegro', acronym: 'ME')
      Addresses::Country.find_or_create_by(id: 131, name: 'Namíbia', acronym: 'NA')
      Addresses::Country.find_or_create_by(id: 132, name: 'Nauru', acronym: 'NR')
      Addresses::Country.find_or_create_by(id: 133, name: 'Nepal', acronym: 'NP')
      Addresses::Country.find_or_create_by(id: 134, name: 'Nicarágua', acronym: 'NI')
      Addresses::Country.find_or_create_by(id: 135, name: 'Níger', acronym: 'NE')
      Addresses::Country.find_or_create_by(id: 136, name: 'Nigéria', acronym: 'NG')
      Addresses::Country.find_or_create_by(id: 137, name: 'Noruega', acronym: 'NO')
      Addresses::Country.find_or_create_by(id: 138, name: 'Nova Zelândia', acronym: 'NZ')
      Addresses::Country.find_or_create_by(id: 139, name: 'Omã', acronym: 'OM')
      Addresses::Country.find_or_create_by(id: 140, name: 'Palau', acronym: 'PW')
      Addresses::Country.find_or_create_by(id: 141, name: 'Palestina', acronym: 'PS')
      Addresses::Country.find_or_create_by(id: 142, name: 'Panamá', acronym: 'PA')
      Addresses::Country.find_or_create_by(id: 143, name: 'Papua-Nova Guiné', acronym: 'PG')
      Addresses::Country.find_or_create_by(id: 144, name: 'Paquistão', acronym: 'PK')
      Addresses::Country.find_or_create_by(id: 145, name: 'Paraguai', acronym: 'PY')
      Addresses::Country.find_or_create_by(id: 146, name: 'Peru', acronym: 'PE')
      Addresses::Country.find_or_create_by(id: 147, name: 'Polônia', acronym: 'PL')
      Addresses::Country.find_or_create_by(id: 148, name: 'Porto Rico', acronym: 'PR')
      Addresses::Country.find_or_create_by(id: 149, name: 'Portugal', acronym: 'PT')
      Addresses::Country.find_or_create_by(id: 150, name: 'Quênia', acronym: 'KE')
      Addresses::Country.find_or_create_by(id: 151, name: 'Quirguistão', acronym: 'KG')
      Addresses::Country.find_or_create_by(id: 152, name: 'Reino Unido', acronym: 'GB')
      Addresses::Country.find_or_create_by(id: 153, name: 'República Centro-Africana', acronym: 'CF')
      Addresses::Country.find_or_create_by(id: 154, name: 'República Checa', acronym: 'CZ')
      Addresses::Country.find_or_create_by(id: 155, name: 'República Democrática do Congo', acronym: 'CD')
      Addresses::Country.find_or_create_by(id: 156, name: 'República Dominicana', acronym: 'DO')
      Addresses::Country.find_or_create_by(id: 157, name: 'Romênia', acronym: 'RO')
      Addresses::Country.find_or_create_by(id: 158, name: 'Ruanda', acronym: 'RW')
      Addresses::Country.find_or_create_by(id: 159, name: 'Rússia', acronym: 'RU')
      Addresses::Country.find_or_create_by(id: 160, name: 'Saara Ocidental', acronym: 'EH')
      Addresses::Country.find_or_create_by(id: 161, name: 'Saint Kitts e Nevis', acronym: 'KN')
      Addresses::Country.find_or_create_by(id: 162, name: 'Saint Pierre e Miquelon', acronym: 'PM')
      Addresses::Country.find_or_create_by(id: 163, name: 'Saint Vincent e Granadinas', acronym: 'VC')
      Addresses::Country.find_or_create_by(id: 164, name: 'Samoa', acronym: 'WS')
      Addresses::Country.find_or_create_by(id: 165, name: 'San Marino', acronym: 'SM')
      Addresses::Country.find_or_create_by(id: 166, name: 'Santa Lúcia', acronym: 'LC')
      Addresses::Country.find_or_create_by(id: 167, name: 'Senegal', acronym: 'SN')
      Addresses::Country.find_or_create_by(id: 168, name: 'Serra Leoa', acronym: 'SL')
      Addresses::Country.find_or_create_by(id: 169, name: 'Sérvia', acronym: 'RS')
      Addresses::Country.find_or_create_by(id: 170, name: 'Síria', acronym: 'SY')
      Addresses::Country.find_or_create_by(id: 171, name: 'Somália', acronym: 'SO')
      Addresses::Country.find_or_create_by(id: 172, name: 'Sri Lanka', acronym: 'LK')
      Addresses::Country.find_or_create_by(id: 173, name: 'Suazilândia', acronym: 'SZ')
      Addresses::Country.find_or_create_by(id: 174, name: 'Sudão', acronym: 'SD')
      Addresses::Country.find_or_create_by(id: 175, name: 'Sudão do Sul', acronym: 'SS')
      Addresses::Country.find_or_create_by(id: 176, name: 'Suécia', acronym: 'SE')
      Addresses::Country.find_or_create_by(id: 177, name: 'Suíça', acronym: 'CH')
      Addresses::Country.find_or_create_by(id: 178, name: 'Suriname', acronym: 'SR')
      Addresses::Country.find_or_create_by(id: 179, name: 'Tailândia', acronym: 'TH')
      Addresses::Country.find_or_create_by(id: 180, name: 'Taiwan', acronym: 'TW')
      Addresses::Country.find_or_create_by(id: 181, name: 'Tajiquistão', acronym: 'TJ')
      Addresses::Country.find_or_create_by(id: 182, name: 'Tanzânia', acronym: 'TZ')
      Addresses::Country.find_or_create_by(id: 183, name: 'Timor-Leste', acronym: 'TL')
      Addresses::Country.find_or_create_by(id: 184, name: 'Togo', acronym: 'TG')
      Addresses::Country.find_or_create_by(id: 185, name: 'Tonga', acronym: 'TO')
      Addresses::Country.find_or_create_by(id: 186, name: 'Trinidad e Tobago', acronym: 'TT')
      Addresses::Country.find_or_create_by(id: 187, name: 'Tunísia', acronym: 'TN')
      Addresses::Country.find_or_create_by(id: 188, name: 'Turcomenistão', acronym: 'TM')
      Addresses::Country.find_or_create_by(id: 189, name: 'Turquia', acronym: 'TR')
      Addresses::Country.find_or_create_by(id: 190, name: 'Tuvalu', acronym: 'TV')
      Addresses::Country.find_or_create_by(id: 191, name: 'Ucrânia', acronym: 'UA')
      Addresses::Country.find_or_create_by(id: 192, name: 'Uganda', acronym: 'UG')
      Addresses::Country.find_or_create_by(id: 193, name: 'Uruguai', acronym: 'UY')
      Addresses::Country.find_or_create_by(id: 194, name: 'Uzbequistão', acronym: 'UZ')
      Addresses::Country.find_or_create_by(id: 195, name: 'Vanuatu', acronym: 'VU')
      Addresses::Country.find_or_create_by(id: 196, name: 'Vaticano', acronym: 'VA')
      Addresses::Country.find_or_create_by(id: 197, name: 'Venezuela', acronym: 'VE')
      Addresses::Country.find_or_create_by(id: 198, name: 'Vietnã', acronym: 'VN')
      Addresses::Country.find_or_create_by(id: 199, name: 'Zâmbia', acronym: 'ZM')
      Addresses::Country.find_or_create_by(id: 200, name: 'Zimbábue', acronym: 'ZW')
    end
  end
end
