# encoding: utf-8

namespace :populate do
  desc 'Populate Coutries'
  task countries: [:environment] do
    puts 'Populating Contries'
    Addresses::Country.find_or_create_by(name: 'Afeganistão', acronym: 'AFG')
    Addresses::Country.find_or_create_by(name: 'África do Sul', acronym: 'AFS')
    Addresses::Country.find_or_create_by(name: 'Antilhas Holandesas', acronym: 'AHL')
    Addresses::Country.find_or_create_by(name: 'Albânia', acronym: 'ALB')
    Addresses::Country.find_or_create_by(name: 'Antigua', acronym: 'ANB')
    Addresses::Country.find_or_create_by(name: 'Andorra', acronym: 'AND')
    Addresses::Country.find_or_create_by(name: 'Angola', acronym: 'ANG')
    Addresses::Country.find_or_create_by(name: 'Arábia Saudita', acronym: 'ARA')
    Addresses::Country.find_or_create_by(name: 'Argentina', acronym: 'ARG')
    Addresses::Country.find_or_create_by(name: 'Argélia', acronym: 'ARL')
    Addresses::Country.find_or_create_by(name: 'Armênia', acronym: 'ARM')
    Addresses::Country.find_or_create_by(name: 'Samoa Americana', acronym: 'ASM')
    Addresses::Country.find_or_create_by(name: 'Antartida', acronym: 'ATC')
    Addresses::Country.find_or_create_by(name: 'Austrália', acronym: 'AUS')
    Addresses::Country.find_or_create_by(name: 'Austria', acronym: 'AUT')
    Addresses::Country.find_or_create_by(name: 'Azerbaijão', acronym: 'AZE')
    Addresses::Country.find_or_create_by(name: 'Barein', acronym: 'BAR')
    Addresses::Country.find_or_create_by(name: 'Belarus', acronym: 'BEA')
    Addresses::Country.find_or_create_by(name: 'Bélgica', acronym: 'BEL')
    Addresses::Country.find_or_create_by(name: 'Benin', acronym: 'BEN')
    Addresses::Country.find_or_create_by(name: 'Bermudas', acronym: 'BER')
    Addresses::Country.find_or_create_by(name: 'Bangladesh', acronym: 'BGD')
    Addresses::Country.find_or_create_by(name: 'Bahamas', acronym: 'BHS')
    Addresses::Country.find_or_create_by(name: 'Birmânia', acronym: 'BIR')
    Addresses::Country.find_or_create_by(name: 'Burkina Fasso', acronym: 'BKF')
    Addresses::Country.find_or_create_by(name: 'Belize', acronym: 'BLZ')
    Addresses::Country.find_or_create_by(name: 'Bolívia', acronym: 'BOL')
    Addresses::Country.find_or_create_by(name: 'Bósnia', acronym: 'BOS')
    Addresses::Country.find_or_create_by(name: 'Botsuana', acronym: 'BOT')
    Addresses::Country.find_or_create_by(name: 'Brasil', acronym: 'BRA')
    Addresses::Country.find_or_create_by(name: 'Barbados', acronym: 'BRB')
    Addresses::Country.find_or_create_by(name: 'Brunei', acronym: 'BRN')
    Addresses::Country.find_or_create_by(name: 'Bulgária', acronym: 'BUL')
    Addresses::Country.find_or_create_by(name: 'Burundi', acronym: 'BUR')
    Addresses::Country.find_or_create_by(name: 'Butão', acronym: 'BUT')
    Addresses::Country.find_or_create_by(name: 'Camarões', acronym: 'CAM')
    Addresses::Country.find_or_create_by(name: 'Canadá', acronym: 'CAN')
    Addresses::Country.find_or_create_by(name: 'Catar', acronym: 'CAT')
    Addresses::Country.find_or_create_by(name: 'Cazaquistão', acronym: 'CAZ')
    Addresses::Country.find_or_create_by(name: 'Camboja', acronym: 'CBJ')
    Addresses::Country.find_or_create_by(name: 'Cabo Verde', acronym: 'CBV')
    Addresses::Country.find_or_create_by(name: 'Ilhas Cocos', acronym: 'CCK')
    Addresses::Country.find_or_create_by(name: 'Chade', acronym: 'CHA')
    Addresses::Country.find_or_create_by(name: 'Chile', acronym: 'CHL')
    Addresses::Country.find_or_create_by(name: 'China', acronym: 'CHN')
    Addresses::Country.find_or_create_by(name: 'Chipre', acronym: 'CHP')
    Addresses::Country.find_or_create_by(name: 'Cingapura', acronym: 'CIN')
    Addresses::Country.find_or_create_by(name: 'Costa do Marfim', acronym: 'CMF')
    Addresses::Country.find_or_create_by(name: 'Ilhas Cook', acronym: 'COK')
    Addresses::Country.find_or_create_by(name: 'Colômbia', acronym: 'COL')
    Addresses::Country.find_or_create_by(name: 'Comores', acronym: 'COM')
    Addresses::Country.find_or_create_by(name: 'Congo', acronym: 'CON')
    Addresses::Country.find_or_create_by(name: 'Costa Rica', acronym: 'CRC')
    Addresses::Country.find_or_create_by(name: 'Coréia do Norte', acronym: 'CRN')
    Addresses::Country.find_or_create_by(name: 'Croácia', acronym: 'CRO')
    Addresses::Country.find_or_create_by(name: 'Coréia do Sul', acronym: 'CRS')
    Addresses::Country.find_or_create_by(name: 'Cuba', acronym: 'CUB')
    Addresses::Country.find_or_create_by(name: 'Christmas Island', acronym: 'CXR')
    Addresses::Country.find_or_create_by(name: 'Ilhas Cayman', acronym: 'CYM')
    Addresses::Country.find_or_create_by(name: 'Dinamarca', acronym: 'DIN')
    Addresses::Country.find_or_create_by(name: 'Djibuti', acronym: 'DJI')
    Addresses::Country.find_or_create_by(name: 'República Dominicana', acronym: 'DOM')
    Addresses::Country.find_or_create_by(name: 'Dominica', acronym: 'DON')
    Addresses::Country.find_or_create_by(name: 'Emirados Árabes', acronym: 'EAU')
    Addresses::Country.find_or_create_by(name: 'Egito', acronym: 'EGI')
    Addresses::Country.find_or_create_by(name: 'El Salvador', acronym: 'ELS')
    Addresses::Country.find_or_create_by(name: 'Equador', acronym: 'EQU')
    Addresses::Country.find_or_create_by(name: 'Eritréa', acronym: 'ERT')
    Addresses::Country.find_or_create_by(name: 'Escócia', acronym: 'ESC')
    Addresses::Country.find_or_create_by(name: 'Western Sahara', acronym: 'ESH')
    Addresses::Country.find_or_create_by(name: 'Espanha', acronym: 'ESP')
    Addresses::Country.find_or_create_by(name: 'Estônia', acronym: 'EST')
    Addresses::Country.find_or_create_by(name: 'Etiópia', acronym: 'ETP')
    Addresses::Country.find_or_create_by(name: 'Estados Unidos', acronym: 'EUA')
    Addresses::Country.find_or_create_by(name: 'Filipinas', acronym: 'FIL')
    Addresses::Country.find_or_create_by(name: 'Finlândia', acronym: 'FIN')
    Addresses::Country.find_or_create_by(name: 'Fiji', acronym: 'FJI')
    Addresses::Country.find_or_create_by(name: 'Ilhas Falkland', acronym: 'FLK')
    Addresses::Country.find_or_create_by(name: 'Formosa', acronym: 'FOR')
    Addresses::Country.find_or_create_by(name: 'França', acronym: 'FRA')
    Addresses::Country.find_or_create_by(name: 'Micronésia', acronym: 'FSM')
    Addresses::Country.find_or_create_by(name: 'Gabão', acronym: 'GAB')
    Addresses::Country.find_or_create_by(name: 'Gales', acronym: 'GAL')
    Addresses::Country.find_or_create_by(name: 'Gâmbia', acronym: 'GAM')
    Addresses::Country.find_or_create_by(name: 'Gana', acronym: 'GAN')
    Addresses::Country.find_or_create_by(name: 'Grã-Bretanha', acronym: 'GBR')
    Addresses::Country.find_or_create_by(name: 'Guadalupe', acronym: 'GDL')
    Addresses::Country.find_or_create_by(name: 'Geórgia', acronym: 'GEO')
    Addresses::Country.find_or_create_by(name: 'Guiana Francesa', acronym: 'GFR')
    Addresses::Country.find_or_create_by(name: 'Gibraltar', acronym: 'GIB')
    Addresses::Country.find_or_create_by(name: 'Guiné Bissau', acronym: 'GNB')
    Addresses::Country.find_or_create_by(name: 'Guiné', acronym: 'GNE')
    Addresses::Country.find_or_create_by(name: 'Guiné Equatorial', acronym: 'GNQ')
    Addresses::Country.find_or_create_by(name: 'Granada', acronym: 'GRD')
    Addresses::Country.find_or_create_by(name: 'Grécia', acronym: 'GRE')
    Addresses::Country.find_or_create_by(name: 'Groênlandia', acronym: 'GRL')
    Addresses::Country.find_or_create_by(name: 'Guatemala', acronym: 'GUA')
    Addresses::Country.find_or_create_by(name: 'Guiana', acronym: 'GUI')
    Addresses::Country.find_or_create_by(name: 'Guam', acronym: 'GUM')
    Addresses::Country.find_or_create_by(name: 'Hong Kong', acronym: 'HKG')
    Addresses::Country.find_or_create_by(name: 'Holanda', acronym: 'HOL')
    Addresses::Country.find_or_create_by(name: 'Honduras', acronym: 'HON')
    Addresses::Country.find_or_create_by(name: 'Haiti', acronym: 'HTI')
    Addresses::Country.find_or_create_by(name: 'Hungria', acronym: 'HUN')
    Addresses::Country.find_or_create_by(name: 'Indonésia', acronym: 'IDN')
    Addresses::Country.find_or_create_by(name: 'Iêmem', acronym: 'IEM')
    Addresses::Country.find_or_create_by(name: 'Ilhas Faroe', acronym: 'IFA')
    Addresses::Country.find_or_create_by(name: 'Ilhas Marshall', acronym: 'IMH')
    Addresses::Country.find_or_create_by(name: 'Iêmen do Sul', acronym: 'IMS')
    Addresses::Country.find_or_create_by(name: 'Índia', acronym: 'IND')
    Addresses::Country.find_or_create_by(name: 'Inglaterra', acronym: 'ING')
    Addresses::Country.find_or_create_by(name: 'Britsh Indian Ocean', acronym: 'IOT')
    Addresses::Country.find_or_create_by(name: 'Irã', acronym: 'IRA')
    Addresses::Country.find_or_create_by(name: 'Irlanda', acronym: 'IRL')
    Addresses::Country.find_or_create_by(name: 'Irlanda do Norte', acronym: 'IRN')
    Addresses::Country.find_or_create_by(name: 'Iraque', acronym: 'IRQ')
    Addresses::Country.find_or_create_by(name: 'Islândia', acronym: 'ISL')
    Addresses::Country.find_or_create_by(name: 'Israel', acronym: 'ISR')
    Addresses::Country.find_or_create_by(name: 'Itália', acronym: 'ITA')
    Addresses::Country.find_or_create_by(name: 'Iugoslávia', acronym: 'IUG')
    Addresses::Country.find_or_create_by(name: 'Ilhas Vírgens EUA', acronym: 'IVA')
    Addresses::Country.find_or_create_by(name: 'Jamaica', acronym: 'JAM')
    Addresses::Country.find_or_create_by(name: 'Japão', acronym: 'JAP')
    Addresses::Country.find_or_create_by(name: 'Jordânia', acronym: 'JOR')
    Addresses::Country.find_or_create_by(name: 'Kiribati', acronym: 'KIR')
    Addresses::Country.find_or_create_by(name: 'São Cristóvão Nevis', acronym: 'KNA')
    Addresses::Country.find_or_create_by(name: 'Kuweit', acronym: 'KWT')
    Addresses::Country.find_or_create_by(name: 'Laos', acronym: 'LAO')
    Addresses::Country.find_or_create_by(name: 'Líbano', acronym: 'LBN')
    Addresses::Country.find_or_create_by(name: 'Libéria', acronym: 'LBR')
    Addresses::Country.find_or_create_by(name: 'Santa Lúcia', acronym: 'LCA')
    Addresses::Country.find_or_create_by(name: 'Lesoto', acronym: 'LES')
    Addresses::Country.find_or_create_by(name: 'Letônia', acronym: 'LET')
    Addresses::Country.find_or_create_by(name: 'Líbia', acronym: 'LIB')
    Addresses::Country.find_or_create_by(name: 'Liechtenstein', acronym: 'LIE')
    Addresses::Country.find_or_create_by(name: 'Lituânia', acronym: 'LIT')
    Addresses::Country.find_or_create_by(name: 'Luxemburgo', acronym: 'LUX')
    Addresses::Country.find_or_create_by(name: 'Macau', acronym: 'MAC')
    Addresses::Country.find_or_create_by(name: 'Madagascar', acronym: 'MAD')
    Addresses::Country.find_or_create_by(name: 'Malásia', acronym: 'MAL')
    Addresses::Country.find_or_create_by(name: 'Marrocos', acronym: 'MAR')
    Addresses::Country.find_or_create_by(name: 'Maurício', acronym: 'MAU')
    Addresses::Country.find_or_create_by(name: 'Moçambique', acronym: 'MBQ')
    Addresses::Country.find_or_create_by(name: 'Macedônia', acronym: 'MCD')
    Addresses::Country.find_or_create_by(name: 'Maldivas', acronym: 'MDV')
    Addresses::Country.find_or_create_by(name: 'México', acronym: 'MEX')
    Addresses::Country.find_or_create_by(name: 'Mongólia', acronym: 'MGL')
    Addresses::Country.find_or_create_by(name: 'Ilhas Midway', acronym: 'MID')
    Addresses::Country.find_or_create_by(name: 'Mali', acronym: 'MLI')
    Addresses::Country.find_or_create_by(name: 'Malta', acronym: 'MLT')
    Addresses::Country.find_or_create_by(name: 'Malavi', acronym: 'MLV')
    Addresses::Country.find_or_create_by(name: 'Mianmar', acronym: 'MMR')
    Addresses::Country.find_or_create_by(name: 'Moldova', acronym: 'MOL')
    Addresses::Country.find_or_create_by(name: 'Mônaco', acronym: 'MON')
    Addresses::Country.find_or_create_by(name: 'Martinica', acronym: 'MRT')
    Addresses::Country.find_or_create_by(name: 'Montserrat', acronym: 'MSR')
    Addresses::Country.find_or_create_by(name: 'Mauritânia', acronym: 'MTN')
    Addresses::Country.find_or_create_by(name: 'Namíbia', acronym: 'NAM')
    Addresses::Country.find_or_create_by(name: 'Nova Caledônia', acronym: 'NCL')
    Addresses::Country.find_or_create_by(name: 'Ilhas Norfolk', acronym: 'NFK')
    Addresses::Country.find_or_create_by(name: 'Nigéria', acronym: 'NGA')
    Addresses::Country.find_or_create_by(name: 'Nicarágua', acronym: 'NIC')
    Addresses::Country.find_or_create_by(name: 'Niger', acronym: 'NIG')
    Addresses::Country.find_or_create_by(name: 'Niue', acronym: 'NIU')
    Addresses::Country.find_or_create_by(name: 'Noruega', acronym: 'NOR')
    Addresses::Country.find_or_create_by(name: 'Nepal', acronym: 'NPL')
    Addresses::Country.find_or_create_by(name: 'Nauru', acronym: 'NRU')
    Addresses::Country.find_or_create_by(name: 'Nova Zelândia', acronym: 'NZL')
    Addresses::Country.find_or_create_by(name: 'Oma', acronym: 'OMA')
    Addresses::Country.find_or_create_by(name: 'Panamá', acronym: 'PAN')
    Addresses::Country.find_or_create_by(name: 'Paquistão', acronym: 'PAQ')
    Addresses::Country.find_or_create_by(name: 'Pacific Islands', acronym: 'PCI')
    Addresses::Country.find_or_create_by(name: 'Pitcairn', acronym: 'PCN')
    Addresses::Country.find_or_create_by(name: 'Peru', acronym: 'PER')
    Addresses::Country.find_or_create_by(name: 'Polinésia Francesa', acronym: 'PLF')
    Addresses::Country.find_or_create_by(name: 'Palau', acronym: 'PLU')
    Addresses::Country.find_or_create_by(name: 'Papua Nova Guiné', acronym: 'PNG')
    Addresses::Country.find_or_create_by(name: 'Polônia', acronym: 'POL')
    Addresses::Country.find_or_create_by(name: 'Portugal', acronym: 'POR')
    Addresses::Country.find_or_create_by(name: 'Paraguai', acronym: 'PRG')
    Addresses::Country.find_or_create_by(name: 'Porto Rico', acronym: 'PTR')
    Addresses::Country.find_or_create_by(name: 'Quênia', acronym: 'QUE')
    Addresses::Country.find_or_create_by(name: 'Quirgistão', acronym: 'QUI')
    Addresses::Country.find_or_create_by(name: 'Rep.Centro-Africana', acronym: 'RCA')
    Addresses::Country.find_or_create_by(name: 'Reunião', acronym: 'REU')
    Addresses::Country.find_or_create_by(name: 'Alemanha', acronym: 'RFA')
    Addresses::Country.find_or_create_by(name: 'Romênia', acronym: 'ROM')
    Addresses::Country.find_or_create_by(name: 'Rússia', acronym: 'RSS')
    Addresses::Country.find_or_create_by(name: 'Ruanda', acronym: 'RUA')
    Addresses::Country.find_or_create_by(name: 'Samoa Ocidental', acronym: 'SAM')
    Addresses::Country.find_or_create_by(name: 'Senegal', acronym: 'SEN')
    Addresses::Country.find_or_create_by(name: 'Ilhas Santa Helena', acronym: 'SHN')
    Addresses::Country.find_or_create_by(name: 'Síria', acronym: 'SIR')
    Addresses::Country.find_or_create_by(name: 'Ilhas Salamão', acronym: 'SLB')
    Addresses::Country.find_or_create_by(name: 'San Marino', acronym: 'SMR')
    Addresses::Country.find_or_create_by(name: 'Somália', acronym: 'SOM')
    Addresses::Country.find_or_create_by(name: 'São Pedro Miquelon', acronym: 'SPM')
    Addresses::Country.find_or_create_by(name: 'Sri Lanka', acronym: 'SRI')
    Addresses::Country.find_or_create_by(name: 'Serra Leoa', acronym: 'SRL')
    Addresses::Country.find_or_create_by(name: 'São Tomé e Príncipe', acronym: 'STP')
    Addresses::Country.find_or_create_by(name: 'Suazilândia', acronym: 'SUA')
    Addresses::Country.find_or_create_by(name: 'Sudão', acronym: 'SUD')
    Addresses::Country.find_or_create_by(name: 'Suécia', acronym: 'SUE')
    Addresses::Country.find_or_create_by(name: 'Suiça', acronym: 'SUI')
    Addresses::Country.find_or_create_by(name: 'Suriname', acronym: 'SUR')
    Addresses::Country.find_or_create_by(name: 'Eslováquia', acronym: 'SVK')
    Addresses::Country.find_or_create_by(name: 'Eslovênia', acronym: 'SVN')
    Addresses::Country.find_or_create_by(name: 'Seychelles', acronym: 'SYC')
    Addresses::Country.find_or_create_by(name: 'Tadjaquistão', acronym: 'TAD')
    Addresses::Country.find_or_create_by(name: 'Tailândia', acronym: 'TAI')
    Addresses::Country.find_or_create_by(name: 'Tanzânia', acronym: 'TAN')
    Addresses::Country.find_or_create_by(name: 'Ilhas Turcas Caicos', acronym: 'TCA')
    Addresses::Country.find_or_create_by(name: 'República Tcheca', acronym: 'TCH')
    Addresses::Country.find_or_create_by(name: 'Togo', acronym: 'TGO')
    Addresses::Country.find_or_create_by(name: 'Tokelau', acronym: 'TKL')
    Addresses::Country.find_or_create_by(name: 'Timor', acronym: 'TMP')
    Addresses::Country.find_or_create_by(name: 'Tonga', acronym: 'TON')
    Addresses::Country.find_or_create_by(name: 'Trinidad e Tobago', acronym: 'TRT')
    Addresses::Country.find_or_create_by(name: 'Turcomenistão', acronym: 'TUC')
    Addresses::Country.find_or_create_by(name: 'Tunísia', acronym: 'TUN')
    Addresses::Country.find_or_create_by(name: 'Turquia', acronym: 'TUR')
    Addresses::Country.find_or_create_by(name: 'Tuvalu', acronym: 'TUV')
    Addresses::Country.find_or_create_by(name: 'Ucrânia', acronym: 'UCR')
    Addresses::Country.find_or_create_by(name: 'Uganda', acronym: 'UGA')
    Addresses::Country.find_or_create_by(name: 'União Soviética', acronym: 'URS')
    Addresses::Country.find_or_create_by(name: 'Uruguai', acronym: 'URU')
    Addresses::Country.find_or_create_by(name: 'Uzbekistan', acronym: 'UZB')
    Addresses::Country.find_or_create_by(name: 'Vaticano', acronym: 'VAT')
    Addresses::Country.find_or_create_by(name: 'São Vicente Granadi', acronym: 'VCT')
    Addresses::Country.find_or_create_by(name: 'Venezuela', acronym: 'VEN')
    Addresses::Country.find_or_create_by(name: 'Ilhas Vírgens GBR', acronym: 'VGB')
    Addresses::Country.find_or_create_by(name: 'Vietnã', acronym: 'VTN')
    Addresses::Country.find_or_create_by(name: 'Vanuatu', acronym: 'VUT')
    Addresses::Country.find_or_create_by(name: 'Ilhas Wake', acronym: 'WAK')
    Addresses::Country.find_or_create_by(name: 'Ilhas Wallis Futuna', acronym: 'WLF')
    Addresses::Country.find_or_create_by(name: 'Zâmbia', acronym: 'ZAN')
    Addresses::Country.find_or_create_by(name: 'Zaire', acronym: 'ZAR')
    Addresses::Country.find_or_create_by(name: 'Zimbabue', acronym: 'ZIN')
  end

end
